platform: linux
inputs:
  - name: repo
  - name: handbrake-release
  - name: linuxdeployqt
outputs:
  - name: bin
image_resource:
  type: docker-image
  source:
    repository: mastercactapus/build-env
    tag: stretch-amd64
run:
  path: repo/handbrake/app/build.sh
