platform: linux
inputs:
  - name: repo
  - name: AppImageKit
outputs:
  - name: bin
image_resource:
  type: docker-image
  source:
    repository: mastercactapus/build-env
    tag: stretch-amd64
run:
  path: repo/appimagekit/runtime/build.sh
