platform: linux
inputs:
  - name: repo
  - name: easel
  - name: easel-driver-repo
  - name: node
  - name: appimagekit-bin
outputs:
  - name: bin
image_resource:
  type: docker-image
  source:
    repository: ubuntu
run:
  path: repo/easel/driver/build.sh
