platform: linux
inputs:
  - name: repo
  - name: src
  - name: build-repo
  - name: node
  - name: AppImageKit
outputs:
  - name: bin
image_resource:
  type: docker-image
  source:
    repository: ubuntu
run:
  path: repo/easel/build.sh
