platform: linux
inputs:
  - name: repo
  - name: makemkv
outputs:
  - name: bin
image_resource:
  type: docker-image
  source:
    repository: mastercactapus/makemkv-build-env
    tag: deb
run:
  path: repo/makemkv/build-deb/build.sh
